# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean App Platform
        run: |
          doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} \
            --spec .do/app.yaml \
            --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} \
            --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
